package com.shomen.MUChat.Utils;

/**
 * Created by USER on 1/29/2016.
 */
public enum EventType {
    STOP_TYPING,NEW_MESSAGE,USER_LEFT,USER_JOINED,YOU_ARE_JOINED,TYPING,CONNECTION_ERROR,CLEAR_NOTI,
    LEAVE_ROOM,DISCONNECTED,CONNECTED,RECONNECTED
}
